### ISSUE TITLE
Randomness in output classification

### ISSUE THREAD

**Issue by robvanderg** [aritter/twitter_nlp#18]
When I run the named entity tagger twice with --classify the outputs are quite different. Out of 250 sentences, 50 sentences are tagged different. Is there something wrong with my build?, or is this normal behaviour?

This makes it very hard to use this tagger as a preprocessing step, and reproduce the results.

**Comment by aritter** [comment]
Hey robvanderg, this is normal behavior.  It's using gibbs sampling for the entity classification, I suppose this could be avoided by seeding the random number generator...
