### ISSUE TITLE
Got error when running "cat test.1k.txt | python python/ner/extractEntities2.py"

### ISSUE THREAD

**Issue by nurdo** [aritter/twitter_nlp#3]
Hi, 

I was trying out twitter_nlp, doing what's in the readme. I got the following error. Can you show me how to go around it?

.//python/cap/cap_classify: 1: .//python/cap/cap_classify: Syntax error: ")" unexpected
Traceback (most recent call last):
  File "python/ner/extractEntities2.py", line 131, in <module>
    goodCap = capClassifier.Classify(words) > 0.9
  File ".//python/cap/cap_classifier.py", line 33, in Classify
    self.capClassifier.stdin.write("%s\n" % self.fe.Extract(' '.join(words)))
IOError: [Errno 32] Broken pipe

**Comment by nupurkmr9** [comment]
@ravs did you solved the problem of getting error in TinySVM. I am also getting the same thing on Mac OS X
